---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-defrag
  namespace: kube-system
spec:
  schedule: "30 3 * * *" # Every night at 3:30 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 1
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          hostNetwork: true
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          containers:
            - name: etcd-defrag
              image: ghcr.io/siderolabs/etcd-defrag:v0.2.0
              args:
                - --endpoints=https://10.0.1.2:2379,https://10.0.1.3:2379,https://10.0.1.7:2379
                - --cacert=/etc/etcd/certs/ca.crt
                - --cert=/etc/etcd/certs/peer.crt
                - --key=/etc/etcd/certs/peer.key
                - --defrag-rule=dbQuotaUsage > 0.5 || dbSize - dbSizeInUse > 100*1024*1024
                - --cluster
              volumeMounts:
                - name: etcd-certs
                  mountPath: /etc/etcd/certs
                  readOnly: true
          volumes:
            - name: etcd-certs
              hostPath:
                path: /system/secrets/etcd
                type: Directory
