---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name renovate-bot-pem
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
  data:
    - secretKey: private_key_pem
      remoteRef:
        decodingStrategy: Base64
        key: /renovate
        property: BOT_APP_PRIVATE_KEY
