---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app pgadmin
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kanidm
      namespace: security
    - name: external-secrets-stores
      namespace: external-secrets
    - name: volsync
      namespace: storage
    - name: kopiur
      namespace: kopiur-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/database/pgadmin/app
  postBuild:
    substitute:
      APP: *app
      CLAIM: pgadmin-v2
      GATUS_SUBDOMAIN: pg
      KANIDM_APP_ICON: https://cdn.jsdelivr.net/gh/selfhst/icons/png/pgadmin.png
      KANIDM_CLIENT_ID_KEY: OIDC_CLIENT_ID
      KANIDM_CLIENT_SECRET_KEY: OIDC_CLIENT_SECRET
      KANIDM_GROUP: household
      KANIDM_ORIGIN_HOST: pg.rafaribe.com
      KANIDM_REDIRECT_PATH: oauth2/authorize
      VOLSYNC_CAPACITY: 2Gi
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: true
  components:
    - ../../../../components/kanidm
    - ../../../../components/volsync
    - ../../../../components/kopiur/snapshot-only
