---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app media-browser
spec:
  chartRef:
    kind: OCIRepository
    name: media-browser-app
  interval: 30m
  values:
    controllers:
      media-browser:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gtsteffaniak/filebrowser
              tag: 1.4.0-stable@sha256:2cd949cd06c058576773c5b8400c854478a64c4f364b1e2bea275819847f099b
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsGroup: 1000
            runAsUser: 1000
    configMaps:
      config:
        data:
          config.yaml: |
            server:
              port: 80
              sources:
                - path: /media
                  config:
                    defaultEnabled: true
            auth:
              method: noauth
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /home/filebrowser/data
      config-file:
        type: configMap
        name: media-browser-config
        globalMounts:
          - path: /home/filebrowser/data/config.yaml
            subPath: config.yaml
            readOnly: true
      media:
        type: nfs
        server: truenas.rafaribe.com
        path: /mnt/tank/media
        globalMounts:
          - path: /media
    route:
      app:
        annotations:
          hajimari.io/icon: mdi:folder-play-outline
        hostnames: ["media.rafaribe.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: media-browser
                port: 80
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
