---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name slink
spec:
  dataFrom:
    - extract:
        key: /slink
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        ADMIN_EMAIL: "{{ .ADMIN_EMAIL }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        ADMIN_USERNAME: "{{ .ADMIN_USERNAME }}"
      engineVersion: v2
