---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: kanidm-upstream
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: kanidm
  validation:
    hostname: idm.rafaribe.com
    wellKnownCACertificates: System
