---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-persons
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: kanidm-persons-secret
    template:
      data:
        KANIDM_RAFARIBE_EMAIL: "{{ .KANIDM_RAFARIBE_EMAIL }}"
        KANIDM_FILIPA_EMAIL: "{{ .KANIDM_FILIPA_EMAIL }}"
  dataFrom:
    - extract:
        key: /kanidm-persons
