---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kaniop.rs/kanidmgroup_v1beta1.json
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: admins
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  members:
    - ${KANIDM_RAFARIBE_USERNAME}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kaniop.rs/kanidmgroup_v1beta1.json
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: household
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  members:
    - ${KANIDM_RAFARIBE_USERNAME}
    - ${KANIDM_WIFE_USERNAME}
