---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app romm
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: games
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kanidm
      namespace: security
  interval: 30m
  path: ./kubernetes/apps/games/romm/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: romm
      KANIDM_APP_ICON: https://cdn.jsdelivr.net/gh/selfhst/icons/png/romm.png
      KANIDM_CLIENT_ID_KEY: OIDC_CLIENT_ID
      KANIDM_CLIENT_SECRET_KEY: OIDC_CLIENT_SECRET
      KANIDM_GROUP: household
      KANIDM_ORIGIN_HOST: romm.rafaribe.com
      KANIDM_REDIRECT_PATH: api/oauth/openid
      VOLSYNC_CAPACITY: 50Gi
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 3m
  components:
    - ../../../../components/kanidm
    - ../../../../components/volsync
    - ../../../../components/dragonfly
