---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: Restore
metadata:
  name: ${APP}
spec:
  policy:
    onMissingSnapshot: Continue
  source:
    fromPolicy:
      name: ${APP}
      offset: 0
  target:
    populator: {}
