---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  credentialProjection:
    enabled: true
  mover:
    securityContext:
      runAsGroup: ${KOPIUR_PGID:=1000}
      runAsUser: ${KOPIUR_PUID:=1000}
  repository:
    kind: ClusterRepository
    name: truenas
  retention:
    keepDaily: 7
    keepHourly: 24
    keepLatest: 3
    keepWeekly: 4
  sources:
    - pvc:
        name: ${CLAIM:=${APP}}
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-blockpool}
