---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name obsidian-couchdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: obsidian-couchdb-secret
    template:
      engineVersion: v2
      data:
        couchdb-user: "{{ .COUCHDB_USER }}"
        couchdb-password: "{{ .COUCHDB_PASSWORD }}"
  dataFrom:
    - extract:
        key: /obsidian-couchdb
