---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app obsidian-couchdb
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      obsidian-couchdb:
        annotations:
          reloader.stakater.com/auto: "true"
        type: statefulset
        pod:
          securityContext:
            fsGroup: 5984
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 5984
            runAsUser: 5984
        initContainers:
          init-config:
            image:
              repository: ghcr.io/home-operations/busybox
              tag: 1.38@sha256:7e2c04dd50ede647bf4a7a4c8dbd629dd4971cd139b9b88fb22bfc3c7a6c13df
            command:
              - "/bin/sh"
              - "-c"
              - "cp /tmp/config/*.ini /opt/couchdb/etc/default.d/; ls -lrt /opt/couchdb/etc/default.d;"
        containers:
          app:
            image:
              repository: docker.io/library/couchdb
              tag: 3.5.2@sha256:3d084addff475d306e649594c0c160e15061288ea7cebf7aee7423201ccd1137
            env:
              COUCHDB_USER:
                valueFrom:
                  secretKeyRef:
                    name: obsidian-couchdb-secret
                    key: couchdb-user
              COUCHDB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: obsidian-couchdb-secret
                    key: couchdb-password
            resources:
              requests:
                cpu: 15m
                memory: 200Mi
              limits:
                memory: 200Mi
    service:
      app:
        controller: obsidian-couchdb
        ports:
          http:
            port: &httpPort 5984
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Services
          gethomepage.dev/name: Obsidian CouchDB
          gethomepage.dev/icon: couchdb.png
          gethomepage.dev/description: CouchDB backend for Obsidian LiveSync
        hostnames:
          - "obsidian.rafaribe.com"
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *httpPort
    persistence:
      config:
        type: configMap
        name: obsidian-couchdb-configmap
        advancedMounts:
          obsidian-couchdb:
            init-config:
              - path: /tmp/config
      config-storage:
        type: emptyDir
        globalMounts:
          - path: /opt/couchdb/etc/default.d
      data:
        existingClaim: obsidian-couchdb
        advancedMounts:
          obsidian-couchdb:
            app:
              - path: /opt/couchdb/data
