---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  inhibitRules:
    - equal:
        - alertname
        - namespace
      sourceMatch:
        - matchType: "="
          name: severity
          value: critical
      targetMatch:
        - matchType: "="
          name: severity
          value: warning
  receivers:
    - name: "null"
    - discordConfigs:
        - apiURL:
            key: DISCORD_WEBHOOK_URL
            name: alertmanager-secret
          message: |-
            {{- range .Alerts }}
            **Alert:** {{ .Labels.alertname }}
            **Severity:** {{ if eq .Labels.severity "critical" }}🚨 Critical{{ else if eq .Labels.severity "warning" }}⚠️ Warning{{ else }}ℹ️ {{ .Labels.severity }}{{ end }}
            **Namespace:** `{{ .Labels.namespace }}`
            {{- if ne .Annotations.description "" }}
            **Description:** {{ .Annotations.description }}
            {{- else if ne .Annotations.summary "" }}
            **Summary:** {{ .Annotations.summary }}
            {{- else if ne .Annotations.message "" }}
            **Message:** {{ .Annotations.message }}
            {{- end }}
            {{- if ne .Labels.pod "" }}
            **Pod:** `{{ .Labels.pod }}`
            {{- end }}
            {{- if ne .Labels.node "" }}
            **Node:** `{{ .Labels.node }}`
            {{- end }}
            ---
            {{- end }}
          sendResolved: true
          title: >-
            {{ if eq .Status "firing" }}🔥{{ else }}✅{{ end }} [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
      name: discord
  route:
    groupBy:
      - alertname
      - job
    groupInterval: 5m
    groupWait: 1m
    receiver: discord
    repeatInterval: 12h
    routes:
      - matchers:
          - matchType: "="
            name: alertname
            value: InfoInhibitor
        receiver: "null"
      - matchers:
          - matchType: "="
            name: alertname
            value: Watchdog
        receiver: "null"

