---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  inhibitRules:
    - equal:
        - alertname
        - namespace
      sourceMatch:
        - matchType: "="
          name: severity
          value: critical
      targetMatch:
        - matchType: "="
          name: severity
          value: warning
  receivers:
    - name: "null"
    - discordConfigs:
        - apiURL:
            key: DISCORD_WEBHOOK_URL
            name: alertmanager-secret
          sendResolved: true
          title: >-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          message: |-
            {{- range .Alerts }}
              {{- if ne .Annotations.description "" }}
                {{ .Annotations.description }}
              {{- else if ne .Annotations.summary "" }}
                {{ .Annotations.summary }}
              {{- else if ne .Annotations.message "" }}
                {{ .Annotations.message }}
              {{- else }}
                Alert description not available
              {{- end }}
            {{- end }}
      name: discord
    - name: pushover
      pushoverConfigs:
        - html: true
          message: |-
            {{- range .Alerts }}
              {{- if ne .Annotations.description "" }}
                {{ .Annotations.description }}
              {{- else if ne .Annotations.summary "" }}
                {{ .Annotations.summary }}
              {{- else if ne .Annotations.message "" }}
                {{ .Annotations.message }}
              {{- else }}
                Alert description not available
              {{- end }}
              {{- if gt (len .Labels.SortedPairs) 0 }}
                <small>
                  {{- range .Labels.SortedPairs }}
                    <b>{{ .Name }}:</b> {{ .Value }}
                  {{- end }}
                </small>
              {{- end }}
            {{- end }}
          priority: |-
            {{ if eq .Status "firing" }}1{{ else }}0{{ end }}
          sendResolved: true
          sound: gamelan
          title: >-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          token:
            key: ALERTMANAGER_PUSHOVER_TOKEN
            name: alertmanager-secret
          ttl: 86400s
          urlTitle: View in Alertmanager
          userKey:
            key: PUSHOVER_USER_KEY
            name: alertmanager-secret
  route:
    groupBy:
      - alertname
      - job
    groupInterval: 5m
    groupWait: 1m
    receiver: discord
    repeatInterval: 12h
    routes:
      - matchers:
          - matchType: "="
            name: alertname
            value: InfoInhibitor
        receiver: "null"
      - matchers:
          - matchType: "="
            name: alertname
            value: Watchdog
        receiver: "null"
      - continue: true
        matchers:
          - matchType: "="
            name: severity
            value: critical
        receiver: pushover
