apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name alertmanager-secret
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        ALERTMANAGER_PUSHOVER_TOKEN: "{{ .ALERTMANAGER_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        PUSHOVER_API_TOKEN: "{{ .ALERTMANAGER_PUSHOVER_TOKEN }}"
        PUSHOVER_API_USERKEY: "{{ .PUSHOVER_USER_KEY }}"
        BUDDY_HEARTBEAT_URL: "{{ .BUDDY_HEARTBEAT_URL }}"
        BUDDY_HEARTBEAT_TOKEN: "{{ .BUDDY_HEARTBEAT_TOKEN }}"
  dataFrom:
    - extract:
        key: /alertmanager
