---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name alertmanager-secret
  namespace: observability
spec:
  dataFrom:
    - extract:
        key: /alertmanager
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    name: *name
    template:
      data:
        DISCORD_WEBHOOK_URL: "{{ .DISCORD_WEBHOOK_URL }}"
      engineVersion: v2
