---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app airtrail
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m
  values:
    controllers:
      airtrail:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              DB_URL: file:/data/airtrail.db
              ORIGIN: https://airtrail.rafaribe.com
              UPLOAD_LOCATION: /data/uploads
            image:
              repository: ghcr.io/johanohly/airtrail
              tag: v3.10.0
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 512Mi
              requests:
                cpu: 10m
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
    persistence:
      data:
        existingClaim: airtrail
        globalMounts:
          - path: /data
      tmp:
        globalMounts:
          - path: /tmp
        type: emptyDir
    route:
      app:
        hostnames:
          - airtrail.rafaribe.com
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: airtrail
                port: 3000
    service:
      app:
        controller: airtrail
        ports:
          http:
            port: 3000
