---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
  annotations:
    kopiur.home-operations.com/allow-identity-change: "true"
spec:
  compression:
    compressor: zstd
  credentialProjection:
    enabled: true
  repository:
    kind: ClusterRepository
    name: truenas
  retention:
    keepDaily: 7
    keepHourly: 24
    keepLatest: 3
    keepWeekly: 4
  sources:
    - pvc:
        name: ${CLAIM:=${APP}}
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-blockpool}
