# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app databasus
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      databasus:
        containers:
          app:
            image:
              repository: docker.io/databasus/databasus
              tag: v3.42.0@sha256:f748c20cecb3cf3162d80ebfddd4f192b5e4ee640d600c9daf726310ac49e51c
            env:
              TZ: "Europe/Lisbon"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 25m
                memory: 128M
              limits:
                memory: 256M
    service:
      app:
        controller: databasus
        ports:
          http:
            port: &port 4005
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /databasus-data
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Database
          gethomepage.dev/name: Databasus
          gethomepage.dev/icon: https://raw.githubusercontent.com/databasus/databasus/main/assets/logo.svg
          gethomepage.dev/description: Database backup tool
          gethomepage.dev/siteMonitor: http://databasus.database:4005
        hostnames: ["databasus.rafaribe.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
