# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
patches:
  - target:
      group: kopiur.home-operations.com
      version: v1alpha1
      kind: SnapshotPolicy
      name: databasus
    patch: |
      - op: add
        path: /spec/mover
        value:
          securityContext:
            runAsUser: 0
