---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name gotify-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        GOTIFY_DEFAULTUSER_NAME: "{{ .GOTIFY_DEFAULTUSER_NAME }}"
        GOTIFY_DEFAULTUSER_PASS: "{{ .GOTIFY_DEFAULTUSER_PASS }}"
  dataFrom:
    - extract:
        key: /gotify
