---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-garage
spec:
  dataFrom:
    - extract:
        key: kopiur
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: kopiur-garage-creds
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .KOPIUR_S3_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .KOPIUR_S3_SECRET_ACCESS_KEY }}"
        KOPIA_PASSWORD: "{{ .KOPIUR_KOPIA_PASSWORD }}"
