---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app syncstorage-rs
  namespace: services
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: database
    - name: external-secrets-stores
      namespace: external-secrets
  interval: 30m
  path: ./kubernetes/apps/services/syncstorage-rs/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: firefox-sync
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: services
  timeout: 5m
  wait: false
