---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kitchenowl
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: services
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kanidm
      namespace: security
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: external-secrets-stores
      namespace: external-secrets
    - name: kopiur
      namespace: kopiur-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/services/kitchenowl/app
  postBuild:
    substitute:
      APP: *app
      APP_GID: "1000"
      APP_UID: "1000"
      CLAIM: kitchenowl-data
      KANIDM_APP_ICON: https://cdn.jsdelivr.net/gh/selfhst/icons/png/kitchenowl.png
      KANIDM_CLIENT_ID_KEY: OIDC_CLIENT_ID
      KANIDM_CLIENT_SECRET_KEY: OIDC_CLIENT_SECRET
      KANIDM_GROUP: household
      KANIDM_ORIGIN_HOST: kitchenowl.rafaribe.com
      KANIDM_REDIRECT_PATH: signin/redirect
      KOPIUR_CAPACITY: 2Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: true
  components:
    - ../../../../components/kanidm
    - ../../../../components/kopiur/backup-nopvc
