---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret safebucket
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        APP__TOKEN_SECRET: "{{ .APP__TOKEN_SECRET }}"
        APP__ADMIN_EMAIL: "{{ .APP__ADMIN_EMAIL }}"
        APP__ADMIN_PASSWORD: "{{ .APP__ADMIN_PASSWORD }}"
        APP__MFA_ENCRYPTION_KEY: "{{ .APP__MFA_ENCRYPTION_KEY }}"
        STORAGE__TYPE: "{{ .STORAGE__TYPE }}"
        STORAGE__RUSTFS__BUCKET_NAME: "{{ .STORAGE__RUSTFS__BUCKET_NAME }}"
        STORAGE__RUSTFS__ENDPOINT: "{{ .STORAGE__RUSTFS__ENDPOINT }}"
        STORAGE__RUSTFS__EXTERNAL_ENDPOINT: "{{ .STORAGE__RUSTFS__EXTERNAL_ENDPOINT }}"
        STORAGE__RUSTFS__ACCESS_KEY: "{{ .STORAGE__RUSTFS__ACCESS_KEY }}"
        STORAGE__RUSTFS__SECRET_KEY: "{{ .STORAGE__RUSTFS__SECRET_KEY }}"
  dataFrom:
    - extract:
        key: /safebucket
