---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app safebucket
spec:
  dataFrom:
    - extract:
        key: /safebucket
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *app
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        APP__ADMIN_EMAIL: "{{ .ADMIN_EMAIL }}"
        APP__ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        APP__MFA_ENCRYPTION_KEY: "{{ .MFA_ENCRYPTION_KEY }}"
        APP__TOKEN_SECRET: "{{ .TOKEN_SECRET }}"
        STORAGE__RUSTFS__ACCESS_KEY: "{{ .S3_ACCESS_KEY }}"
        STORAGE__RUSTFS__SECRET_KEY: "{{ .S3_SECRET_KEY }}"
