# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: garage-primary
spec:
  backend:
    s3:
      bucket: volsync-kopia
      endpoint: garage.storage.svc.cluster.local:3900
      region: us-east-1
      insecureTLS: true
  auth:
    secretRef:
      name: kopiur-garage-creds
      namespace: storage
  encryption:
    passwordSecretRef:
      name: kopiur-garage-creds
      namespace: storage
      key: KOPIA_PASSWORD
  create:
    enabled: true
  maintenance:
    enabled: true
    schedule:
      quick: { cron: "0 */6 * * *", jitter: 30m }
      full: { cron: "0 3 * * *", jitter: 1h }
  allowedNamespaces:
    - "*"
