---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app explo
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        LISTENBRAINZ_USER: "{{ .LISTENBRAINZ_USER }}"
        LISTENBRAINZ_USER_TOKEN: "{{ .LISTENBRAINZ_USER_TOKEN }}"
        SLSKD_API_KEY: "{{ .SLSKD_API_KEY }}"
        SLSKD_URL: "http://slskd.downloads.svc.cluster.local:80"
        SYSTEM_PASSWORD: "{{ .NAVIDROME_PASSWORD }}"
        SYSTEM_URL: "http://navidrome.media.svc.cluster.local:4533"
        SYSTEM_USERNAME: "{{ .NAVIDROME_USERNAME }}"
        UI_PASSWORD: "{{ .UI_PASSWORD }}"
        UI_USERNAME: "{{ .UI_USERNAME }}"
  dataFrom:
    - extract:
        key: /explo
    - extract:
        key: /navidrome
    - extract:
        key: /slskd
