---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-mcp-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    creationPolicy: Owner
    name: forgejo-mcp-secret
  data:
    - remoteRef:
        key: /forgejo
        property: FORGEJO_MCP_TOKEN
      secretKey: GITEA_TOKEN
