---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app karakeep
spec:
  targetNamespace: services
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/kanidm
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
    - name: kanidm
      namespace: security
    - name: kopiur
      namespace: kopiur-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: "./kubernetes/apps/services/karakeep/app"
  postBuild:
    substitute:
      APP: *app
      KANIDM_APP_ICON: https://cdn.jsdelivr.net/gh/selfhst/icons/png/karakeep.png
      KANIDM_CLIENT_ID_KEY: OAUTH_CLIENT_ID
      KANIDM_CLIENT_SECRET_KEY: OAUTH_CLIENT_SECRET
      KANIDM_GROUP: household
      KANIDM_ORIGIN_HOST: karakeep.rafaribe.com
      KANIDM_REDIRECT_PATH: api/auth/callback/custom
      KOPIUR_CAPACITY: 5Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
