receivers:
  - name: "null"
  - name: "discord"
    discord_configs:
      - webhook_url_file: /etc/secrets/DISCORD_WEBHOOK_URL
        send_resolved: true
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
        message: |-
          {{- range .Alerts }}
            {{- if ne .Labels.severity "" }}
              **Severity:** {{ .Labels.severity }}
            {{- end }}
            {{- if ne .Annotations.description "" }}
              **Description:** {{ .Annotations.description }}
            {{- else if ne .Annotations.summary "" }}
              **Summary:** {{ .Annotations.summary }}
            {{- else if ne .Annotations.message "" }}
              **Message:** {{ .Annotations.message }}
            {{- else }}
              **Description:** N/A
            {{- end }}
          {{- end }}
  - name: "pushover"
    pushover_configs:
      - html: true
        message: |-
          {{- range .Alerts }}
            {{- if ne .Labels.severity "" }}
              <b>Severity:</b> <i>{{ .Labels.severity }}</i>
            {{- else }}
              <b>Severity:</b> <i>N/A</i>
            {{- end }}
            {{- if ne .Annotations.description "" }}
              <b>Description:</b> <i>{{ .Annotations.description }}</i>
            {{- else if ne .Annotations.summary "" }}
              <b>Summary:</b> <i>{{ .Annotations.summary }}</i>
            {{- else if ne .Annotations.message "" }}
              <b>Message:</b> <i>{{ .Annotations.message }}</i>
            {{- else }}
              <b>Description:</b> <i>N/A</i>
            {{- end }}
            {{- if gt (len .Labels.SortedPairs) 0 }}
              <b>Details:</b>
              {{- range .Labels.SortedPairs }}
                • <b>{{ .Name }}:</b> <i>{{ .Value }}</i>
              {{- end }}
            {{- end }}
          {{- end }}
        priority: |-
          {{ if eq .Status "firing" }}1{{ else }}0{{ end }}
        send_resolved: true
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
        token_file: /etc/secrets/PUSHOVER_API_TOKEN
        url_title: View in Alert Manager
        user_key_file: /etc/secrets/PUSHOVER_API_USERKEY

route:
  group_by: ["alertname", "job"]
  group_interval: 5m
  group_wait: 30s
  receiver: "discord"
  repeat_interval: 6h
  routes:
    - matchers:
        - alertname =~ "InfoInhibitor|Watchdog"
      receiver: "null"
    - continue: true
      matchers:
        - severity = critical
      receiver: "pushover"

inhibit_rules:
  - equal: ["alertname", "namespace"]
    source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
