receivers:
  - name: "null"
  - name: "discord"
    discord_configs:
      - webhook_url_file: /etc/secrets/DISCORD_WEBHOOK_URL
        send_resolved: true
        title: |-
          {{ if eq .Status "firing" }}🔥{{ else }}✅{{ end }} [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
        message: |-
          {{- range .Alerts }}
          **Alert:** {{ .Labels.alertname }}
          **Severity:** {{ if eq .Labels.severity "critical" }}🚨 Critical{{ else if eq .Labels.severity "warning" }}⚠️ Warning{{ else }}ℹ️ {{ .Labels.severity }}{{ end }}
          **Namespace:** `{{ .Labels.namespace }}`
          {{- if ne .Annotations.description "" }}
          **Description:** {{ .Annotations.description }}
          {{- else if ne .Annotations.summary "" }}
          **Summary:** {{ .Annotations.summary }}
          {{- else if ne .Annotations.message "" }}
          **Message:** {{ .Annotations.message }}
          {{- end }}
          {{- if ne .Labels.pod "" }}
          **Pod:** `{{ .Labels.pod }}`
          {{- end }}
          {{- if ne .Labels.node "" }}
          **Node:** `{{ .Labels.node }}`
          {{- end }}
          ---
          {{- end }}
  - name: "pushover"
    pushover_configs:
      - html: true
        message: |-
          {{- range .Alerts }}
          {{- if eq .Labels.severity "critical" }}
          <b>🚨 Severity:</b> Critical
          {{- else if eq .Labels.severity "warning" }}
          <b>⚠️ Severity:</b> Warning
          {{- else }}
          <b>ℹ️ Severity:</b> {{ .Labels.severity }}
          {{- end }}
          <b>Namespace:</b> {{ .Labels.namespace }}
          {{- if ne .Annotations.description "" }}
          <b>Description:</b> {{ .Annotations.description }}
          {{- else if ne .Annotations.summary "" }}
          <b>Summary:</b> {{ .Annotations.summary }}
          {{- else if ne .Annotations.message "" }}
          <b>Message:</b> {{ .Annotations.message }}
          {{- end }}
          {{- if ne .Labels.pod "" }}
          <b>Pod:</b> {{ .Labels.pod }}
          {{- end }}
          {{- if ne .Labels.node "" }}
          <b>Node:</b> {{ .Labels.node }}
          {{- end }}
          {{- end }}
        priority: |-
          {{ if eq .Status "firing" }}1{{ else }}0{{ end }}
        send_resolved: true
        title: |-
          {{ if eq .Status "firing" }}🔥{{ else }}✅{{ end }} [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
        token_file: /etc/secrets/PUSHOVER_API_TOKEN
        url_title: View in Alert Manager
        user_key_file: /etc/secrets/PUSHOVER_API_USERKEY

route:
  group_by: ["alertname", "job"]
  group_interval: 5m
  group_wait: 30s
  receiver: "discord"
  repeat_interval: 6h
  routes:
    - matchers:
        - alertname =~ "InfoInhibitor|Watchdog"
      receiver: "null"
    - continue: true
      matchers:
        - severity = critical
      receiver: "pushover"

inhibit_rules:
  - equal: ["alertname", "namespace"]
    source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
