---
# yaml-language-server: $schema=https://ks.hsn.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: memory-mcp
  namespace: flux-system
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: memory-mcp
  components:
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: kopiur
      namespace: kopiur-system
    - name: toolhive-operator-crds
  interval: 1h
  path: ./kubernetes/apps/ai/mcp-servers/memory
  postBuild:
    substitute:
      APP: memory-mcp
      KOPIUR_CAPACITY: 1Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
