---
# yaml-language-server: $schema=https://ks.hsn.dev/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: memory-mcp
spec:
  groupRef:
    name: mcp-tools
  image: ghcr.io/bjw-s-labs/mcp-memory:2026.7.4@sha256:78487a16681b91102197e9b7915f950a148e94ff1ce6356707d3ff6ef6516ae7
  podTemplateSpec:
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: memory-mcp
      containers:
        - name: mcp
          volumeMounts:
            - name: data
              mountPath: /data
  transport: stdio
