---
# yaml-language-server: $schema=https://ks.hsn.dev/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: memory-mcp
spec:
  groupRef:
    name: mcp-tools
  image: ghcr.io/bjw-s-labs/mcp-memory:2026.8.31@sha256:81f1ec66d6c771a516f47705a827b6ac7400e197b4f48b487c3488ee68f2f72d
  podTemplateSpec:
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: memory-mcp
      containers:
        - name: mcp
          volumeMounts:
            - name: data
              mountPath: /data
  transport: stdio
