---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app nodecast-tv
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: nodecast-tv-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # OIDC
        OIDC_ISSUER_URL: "https://idm.rafaribe.com/oauth2/openid/nodecast-tv"
        OIDC_CALLBACK_URL: "https://nodecast-tv.rafaribe.com/api/auth/oidc/callback"
  dataFrom:
    - extract:
        key: /nodecast-tv
