---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docmost-mcp-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: docmost-mcp-secret
    creationPolicy: Owner
  data:
    - secretKey: DOCMOST_EMAIL
      remoteRef:
        key: /docmost
        property: DOCMOST_MCP_EMAIL
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docmost-mcp-secret-password
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: docmost-mcp-secret-password
    creationPolicy: Owner
  data:
    - secretKey: DOCMOST_PASSWORD
      remoteRef:
        key: /docmost
        property: DOCMOST_MCP_PASSWORD
