---
# yaml-language-server: $schema=https://ks.hsn.dev/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: docmost-mcp
spec:
  groupRef:
    name: mcp-tools
  image: ghcr.io/rafaribe/docmost-mcp:v0.2.0@sha256:1bb3292a56b8d07022bcd362537672bfdaea8637ec7aefbc1bb5b0c6918e643a
  env:
    - name: DOCMOST_API_URL
      value: http://docmost.services:3000/api
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          volumeMounts:
            - mountPath: /tmp
              name: tmpfs
      volumes:
        - name: tmpfs
          emptyDir:
            medium: Memory
  secrets:
    - name: docmost-mcp-secret
      key: DOCMOST_EMAIL
    - name: docmost-mcp-secret-password
      key: DOCMOST_PASSWORD
  transport: stdio
