---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ha-mcp-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: ha-mcp-secret
    creationPolicy: Owner
  data:
    - secretKey: HOMEASSISTANT_TOKEN
      remoteRef:
        key: /hass
        property: HASS_API_KEY
