---
# yaml-language-server: $schema=https://ks.hsn.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app open-webui
  namespace: flux-system
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: database
    - name: external-secrets-stores
      namespace: external-secrets
    - name: kanidm
      namespace: security
    - name: kopiur
      namespace: kopiur-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/ai/open-webui/app
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: chat
      KANIDM_APP_ICON: https://cdn.jsdelivr.net/gh/selfhst/icons/png/open-webui.png
      KANIDM_CLIENT_ID_KEY: OAUTH_CLIENT_ID
      KANIDM_CLIENT_SECRET_KEY: OAUTH_CLIENT_SECRET
      KANIDM_GROUP: household
      KANIDM_ORIGIN_HOST: chat.rafaribe.com
      KANIDM_REDIRECT_PATH: oauth/oidc/callback
      KOPIUR_CAPACITY: 5Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
  components:
    - ../../../../components/kanidm
    - ../../../../components/kopiur/backup
