---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name syncstorage-rs
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        # Database Init - Syncstorage
        INIT_POSTGRES_HOST: "home-ops-rw.database.svc.cluster.local"
        INIT_POSTGRES_DBNAME: syncstorage
        INIT_POSTGRES_USER: syncstorage
        INIT_POSTGRES_PASS: "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # App Configuration
        SYNC_MASTER_SECRET: "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
        SYNC_SYNCSTORAGE__DATABASE_URL: "postgres://syncstorage:{{ .POSTGRES_GENERIC_APP_PASSWORD }}@home-ops-rw.database.svc.cluster.local:5432/syncstorage"
        SYNC_TOKENSERVER__DATABASE_URL: "postgres://syncstorage:{{ .POSTGRES_GENERIC_APP_PASSWORD }}@home-ops-rw.database.svc.cluster.local:5432/syncstorage"
  dataFrom:
    - extract:
        key: cloudnativepg
