---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app miniflux
spec:
  targetNamespace: services
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
    - name: kanidm
      namespace: security
  interval: 30m
  path: "./kubernetes/apps/services/miniflux/app"
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: miniflux
      KANIDM_APP_ICON: https://cdn.jsdelivr.net/gh/selfhst/icons/png/miniflux.png
      KANIDM_CLIENT_ID_KEY: OAUTH2_CLIENT_ID
      KANIDM_CLIENT_SECRET_KEY: OAUTH2_CLIENT_SECRET
      KANIDM_GROUP: household
      KANIDM_ORIGIN_HOST: miniflux.rafaribe.com
      KANIDM_REDIRECT_PATH: oauth2/oidc/callback
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
  components:
    - ../../../../components/kanidm
