---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kanidm-secrets
  namespace: flux-system
spec:
  targetNamespace: security
  commonMetadata:
    labels:
      app.kubernetes.io/name: kanidm
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
  interval: 30m
  path: ./kubernetes/apps/security/kanidm/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kanidm
  namespace: flux-system
spec:
  targetNamespace: security
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
    - name: kanidm-secrets
    - name: kaniop
    - name: volsync
      namespace: storage
  interval: 30m
  path: ./kubernetes/apps/security/kanidm/app
  postBuild:
    substitute:
      APP: *app
      KANIDM_RAFARIBE_USERNAME: user1
      KANIDM_RAFARIBE_DISPLAYNAME: User One
      KANIDM_RAFARIBE_LEGALNAME: User One
      KANIDM_RAFARIBE_EMAIL: user1@example.com
      KANIDM_RAFARIBE_EMAIL2: user1-alt@example.com
      KANIDM_WIFE_USERNAME: user2
      KANIDM_WIFE_DISPLAYNAME: User Two
      KANIDM_WIFE_LEGALNAME: User Two
      KANIDM_WIFE_EMAIL: user2@example.com
      KANIDM_WIFE_EMAIL2: user2-alt@example.com
    substituteFrom:
      - kind: Secret
        name: kanidm-persons-secret
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
