---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: gatus-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DISCORD_WEBHOOK_URL: "{{ .DISCORD_WEBHOOK_URL }}"
        PUSHOVER_TOKEN: "{{ .CUSTOM_PUSHOVER_APP_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .CUSTOM_PUSHOVER_USER_KEY }}"
  dataFrom:
    - extract:
        key: /gatus
