---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app netboot
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      netboot:
        containers:
          app:
            image:
              repository: ghcr.io/netbootxyz/netbootxyz
              tag: 0.7.6-nbxyz4
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 3000
      web:
        controller: *app
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.0.1.27
        ports:
          web:
            port: 80
            protocol: HTTP
      tftp:
        controller: *app
        type: NodePort
        ports:
          tftp:
            port: 69
            protocol: UDP
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: "Services"
          gethomepage.dev/name: "Netboot.xyz"
          gethomepage.dev/icon: "https://netboot.xyz/img/netboot.xyz.gif"
          gethomepage.dev/description: "Network boot system for various operating systems"
        hostnames: ["netboot.rafaribe.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: netboot-app
                port: *port
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: netboot
      assets:
        type: emptyDir
