---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopiur
spec:
  chartRef:
    kind: OCIRepository
    name: kopiur
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: ClusterRole
              name: kopiur-mover
            patch: |
              - op: add
                path: /rules/-
                value:
                  apiGroups: ["kopiur.home-operations.com"]
                  resources: ["restores", "snapshotpolicies", "snapshots", "repositories", "clusterrepositories"]
                  verbs: ["get", "list"]
  values:
    features:
      credentialProjection:
        enabled: true
    monitoring:
      prometheusRule:
        enabled: true
      serviceMonitor:
        enabled: true
    podSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 256Mi
