---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-mcp-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: tailscale-mcp-secret
    creationPolicy: Owner
  data:
    - secretKey: MCP_HTTP_BEARER_TOKEN
      remoteRef:
        key: /tailscale
        property: MCP_HTTP_BEARER_TOKEN
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-mcp-oauth-id
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: tailscale-mcp-oauth-id
    creationPolicy: Owner
  data:
    - secretKey: TAILSCALE_OAUTH_CLIENT_ID
      remoteRef:
        key: /tailscale
        property: TAILSCALE_OAUTH_CLIENT_ID
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-mcp-oauth-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: tailscale-mcp-oauth-secret
    creationPolicy: Owner
  data:
    - secretKey: TAILSCALE_OAUTH_CLIENT_SECRET
      remoteRef:
        key: /tailscale
        property: TAILSCALE_OAUTH_CLIENT_SECRET
