# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name grafana
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Authentication
        GF_SECURITY_ADMIN_USER: "{{ .GF_SECURITY_ADMIN_USER }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .GF_SECURITY_ADMIN_PASSWORD }}"
        # OIDC
        GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
        GF_AUTH_GENERIC_OAUTH_NAME: Kanidm
        GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email groups
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://idm.rafaribe.com/ui/oauth2
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://idm.rafaribe.com/oauth2/token
        GF_AUTH_GENERIC_OAUTH_API_URL: https://idm.rafaribe.com/oauth2/openid/grafana/userinfo
        GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
        GF_AUTH_GENERIC_OAUTH_USE_PKCE: "false"
        GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups[*], 'household') && 'GrafanaAdmin' || 'Viewer'"
        GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN: "true"
        GF_AUTH_SIGNOUT_REDIRECT_URL: https://idm.rafaribe.com/ui/oauth2
  dataFrom:
    - extract:
        key: /grafana
