# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name grafana
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Init DB
        INIT_POSTGRES_DBNAME: &dbName "{{ .INIT_POSTGRES_DBNAME }}"
        INIT_POSTGRES_HOST: &dbHost "home-ops-rw.database.svc.cluster.local"
        INIT_POSTGRES_USER: &dbUser "{{ .INIT_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .INIT_POSTGRES_SUPER_PASS }}"
        # Database
        GF_DATABASE_NAME: "{{ .INIT_POSTGRES_DBNAME }}"
        GF_DATABASE_HOST: "home-ops-rw.database.svc.cluster.local:5432"
        GF_DATABASE_USER: "{{ .INIT_POSTGRES_USER }}"
        GF_DATABASE_PASSWORD: "{{ .POSTGRES_GENERIC_APP_PASSWORD }}"
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        # Authentication / OIDC
        GF_SECURITY_ADMIN_USER: "{{ .GF_SECURITY_ADMIN_USER }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .GF_SECURITY_ADMIN_PASSWORD }}"
        GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
        GF_AUTH_GENERIC_OAUTH_NAME: Kanidm
        GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://idm.rafaribe.com/ui/oauth2
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://idm.rafaribe.com/oauth2/token
        GF_AUTH_GENERIC_OAUTH_API_URL: https://idm.rafaribe.com/oauth2/openid/grafana/userinfo
        GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
        GF_AUTH_GENERIC_OAUTH_USE_PKCE: "false"
        GF_AUTH_SIGNOUT_REDIRECT_URL: https://idm.rafaribe.com/ui/oauth2
  dataFrom:
    - extract:
        key: /grafana
    - extract:
        key: /cloudnativepg