---
# yaml-language-server: $schema=https://ks.hsn.dev/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: mealie-mcp
spec:
  groupRef:
    name: mcp-tools
  image: ghcr.io/danielpalstra/mealie-mcp-server-docker:main
  env:
    - name: MEALIE_BASE_URL
      value: http://mealie.services:9000
  podTemplateSpec:
    spec:
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      containers:
        - name: mcp
          volumeMounts:
            - mountPath: /.cache
              name: cache
            - mountPath: /tmp
              name: tmpfs
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
      volumes:
        - name: cache
          emptyDir: {}
        - name: tmpfs
          emptyDir:
            medium: Memory
  secrets:
    - name: mealie-mcp-secret
      key: MEALIE_API_KEY
  transport: stdio
