---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: garage-s3
spec:
  allowedNamespaces:
    all: true
  backend:
    s3:
      bucket: kopiur-backups
      endpoint: 10.0.0.6:3900
      region: us-east-1
      tls:
        disableTls: true
      auth:
        secretRef:
          name: kopiur-garage-creds
          namespace: kopiur-system
  create:
    enabled: true
  credentialProjection:
    allowed: true
  deletionProtection:
    threshold: 25
  encryption:
    passwordSecretRef:
      name: kopiur-garage-creds
      namespace: kopiur-system
      key: KOPIA_PASSWORD
  identityDefaults:
    hostnameExpr: "namespace"
    usernameExpr: "policyName"
  maintenance:
    enabled: true
    schedule:
      full: { cron: "0 3 * * *", jitter: 1h }
      quick: { cron: "0 */6 * * *", jitter: 30m }
  moverDefaults:
    podSecurityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsUser: 1000
    sourceColocation:
      mode: Auto
  parameters:
    epoch:
      minDuration: 6h
  scheduleDefaults:
    timezone: Europe/Lisbon
