---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: garage-s3
  annotations:
    kopiur.home-operations.com/allow-identity-change: "intentional"
spec:
  allowedNamespaces:
    all: true
  backend:
    s3:
      auth:
        secretRef:
          name: kopiur-garage-creds
          namespace: kopiur-system
      bucket: kopiur-backups
      endpoint: 10.0.0.6:3900
      region: us-east-1
      tls:
        disableTls: true
  create:
    enabled: true
  credentialProjection:
    allowed: true
  encryption:
    passwordSecretRef:
      key: KOPIA_PASSWORD
      name: kopiur-garage-creds
      namespace: kopiur-system
  identityDefaults:
    hostnameExpr: namespace
    usernameExpr: policyName
  maintenance:
    enabled: true
    schedule:
      full:
        cron: "0 3 * * *"
        jitter: 1h
      quick:
        cron: "0 */6 * * *"
        jitter: 30m
  mode: ReadWrite
  moverDefaults:
    podSecurityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsUser: 1000
    sourceColocation:
      mode: Auto
  onNamespaceDelete: Orphan
  scheduleDefaults:
    timezone: Europe/Lisbon
