---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name n8n
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        # App
        N8N_ENCRYPTION_KEY: "{{ .SECRET_N8N_ENCRYPTION_KEY }}"

  dataFrom:
    - extract:
        key: /n8n
