---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app atuin
spec:
  targetNamespace: services
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: kopiur
      namespace: kopiur-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 10m
  path: "./kubernetes/apps/services/atuin/app"
  postBuild:
    substitute:
      APP: *app
      DB_NAME: atuin
      DB_USER: atuin
      HOSTNAME: atuin.rafaribe.com
      KOPIUR_CAPACITY: 5Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
