---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: forgejo-admin-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        email: "{{ .FORGEJO_ADMIN_EMAIL }}"
        password: "{{ .FORGEJO_ADMIN_PASSWORD }}"
        username: "{{ .FORGEJO_ADMIN_USER }}"
  dataFrom:
    - extract:
        key: /forgejo
