---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/rbac.authorization.k8s.io/clusterrole_v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reaplet
rules:
  - apiGroups: [""]
    resources: ["events", "nodes", "pods", "pods/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources: ["evictions"]
    verbs: ["create"]
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/rbac.authorization.k8s.io/clusterrolebinding_v1.json
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reaplet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reaplet
subjects:
  - kind: ServiceAccount
    name: reaplet
    namespace: system-controllers
