---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tvheadend
spec:
  chartRef:
    kind: OCIRepository
    name: tvheadend
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      tvheadend:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/tvheadend
              tag: version-80729d2f@sha256:e8715f103ba15eafe360e1c4257dfe8e015e80401bd9ba71bc7663b328e8e9ca
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: Europe/Lisbon
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &httpPort 9981
                  periodSeconds: 30
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *httpPort
                  periodSeconds: 10
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: false
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /config
      recordings:
        type: emptyDir
        globalMounts:
          - path: /recordings
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: tvheadend.png
          gethomepage.dev/name: TVHeadend
        hostnames:
          - tvheadend.rafaribe.com
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: http
    service:
      app:
        controller: *app
        ports:
          http:
            port: *httpPort
          htsp:
            port: 9982
