---
alerting:
  discord:
    webhook-url: ${DISCORD_WEBHOOK_URL}
    default-alert:
      enabled: true
      failure-threshold: 3
      send-on-resolved: true
      description: "health check failed"
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
  - name: Google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
  - name: Quad9
    group: connectivity
    url: icmp://9.9.9.9
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: discord
metrics: true
storage:
  type: sqlite
  caching: true
  path: ${GATUS_CONFIG_PATH}/gatus.db
ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/66985630
  link: https://github.com/rafaribe
web:
  port: ${GATUS_WEB_PORT}
