---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kaniop.rs/kanidmgroup_v1beta1.json
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: karakeep-users
spec:
  kanidmRef:
    name: kanidm
    namespace: security
  members: []
