---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./docmost/ks.yaml
  - ./ha/ks.yaml
  - ./memory/ks.yaml
  - ./paperless/ks.yaml
  - ./tailscale/ks.yaml
