---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name tandoor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      data:
        # General
        SECRET_KEY: "{{ .TANDOOR_SECRET_KEY }}"
        # Database - SQLite stored on PVC
        DB_ENGINE: django.db.backends.sqlite3
        POSTGRES_DB: /opt/recipes/mediafiles/db.sqlite3
        # Email
        EMAIL_HOST: "smtp-relay-noreply.services.svc.cluster.local"
        EMAIL_PORT: "25"
        EMAIL_USE_SSL: "1"
        DEFAULT_FROM_EMAIL: "noreply@rafaribe.com"
        ACCOUNT_EMAIL_SUBJECT_PREFIX: "[Rafaribe Recipes]"
  dataFrom:
    - extract:
        key: /tandoor
