# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/kopiamaintenance_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: daily
  namespace: volsync
spec:
  enabled: true
  activeDeadlineSeconds: 28800 # 8 hours - repo has 6384+ index blobs, full maintenance can take >3h
  trigger:
    schedule: 30 */6 * * *
  repository:
    repository: volsync-maintenance-secret
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
