server:
  port: 8081

theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65
pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: calendar
          - type: weather
            location: Viseu, Portugal
            units: metric
            hour-format: 24h
      - size: full
        widgets:
          - type: rss
            title: News
            feeds:
              - url: https://www.techmeme.com/feed.xml
                title: Techmeme
              - url: https://news.ycombinator.com/rss
                title: Hacker News
          - type: reddit
            subreddit: selfhosted
      - size: small
        widgets:
          - type: monitor
            title: Services
            sites:
              - title: Kanidm
                url: https://idm.rafaribe.com
              - title: Grafana
                url: https://grafana.rafaribe.com
