---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-mcp-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: paperless-mcp-secret
    creationPolicy: Owner
  data:
    - secretKey: PAPERLESS_API_KEY
      remoteRef:
        key: /paperless
        property: PAPERLESS_API_KEY
