---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret leafwiki
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        LEAFWIKI_JWT_SECRET: "{{ .LEAFWIKI_JWT_SECRET }}"
        LEAFWIKI_ADMIN_PASSWORD: "{{ .LEAFWIKI_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: /leafwiki
