---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app linkding
spec:
  targetNamespace: services
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kanidm
      namespace: security
    - name: external-secrets-stores
      namespace: external-secrets
  interval: 30m
  path: "./kubernetes/apps/services/linkding/app"
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: links
      KANIDM_APP_ICON: https://raw.githubusercontent.com/sissbruecker/linkding/master/linkding/static/logo.svg
      KANIDM_CLIENT_ID_KEY: OIDC_RP_CLIENT_ID
      KANIDM_CLIENT_SECRET_KEY: OIDC_RP_CLIENT_SECRET
      KANIDM_GROUP: household
      KANIDM_ORIGIN_HOST: links.rafaribe.com
      KANIDM_REDIRECT_PATH: oidc/callback/
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
  components:
    - ../../../../components/kanidm
