---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/dragonfly
    - ../../../../components/volsync
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      current: status.phase == 'ready'
      failed: status.phase != 'ready'
      kind: Dragonfly
  interval: 30m
  path: ./kubernetes/apps/development/forgejo/app
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 30Gi
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: development
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo-runner
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: forgejo
  interval: 30m
  path: ./kubernetes/apps/development/forgejo/runner
  postBuild:
    substitute:
      APP: *app
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: development
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gickup
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: forgejo
  interval: 30m
  path: ./kubernetes/apps/development/forgejo/gickup/app
  postBuild:
    substitute:
      APP: *app
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: development
  timeout: 5m
  wait: false
