---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/dragonfly
    - ../../../../components/kanidm
    - ../../../../components/kopiur/backup
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
    - name: kanidm
      namespace: security
    - name: kopiur
      namespace: kopiur-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      current: status.phase == 'ready'
      failed: status.phase != 'ready'
      kind: Dragonfly
  interval: 30m
  path: ./kubernetes/apps/development/forgejo/app
  postBuild:
    substitute:
      APP: *app
      CLAIM: forgejo-data
      KANIDM_APP_ICON: https://cdn.jsdelivr.net/gh/selfhst/icons/png/forgejo.png
      KANIDM_CLIENT_ID_KEY: OIDC_CLIENT_ID
      KANIDM_CLIENT_SECRET_KEY: OIDC_CLIENT_SECRET
      KANIDM_GROUP: household
      KANIDM_ORIGIN_HOST: git.rafaribe.com
      KANIDM_REDIRECT_PATH: user/oauth2/kanidm/callback
      KOPIUR_CAPACITY: 50Gi
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: development
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo-runner
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: forgejo
    - name: kopiur
      namespace: kopiur-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/development/forgejo/runner
  postBuild:
    substitute:
      APP: *app
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: development
  timeout: 5m
  wait: false
  components:
