---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-persons
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: kanidm-persons-secret
    template:
      data:
        KANIDM_RAFARIBE_DISPLAYNAME: "{{ .KANIDM_RAFARIBE_DISPLAYNAME }}"
        KANIDM_RAFARIBE_EMAIL: "{{ .KANIDM_RAFARIBE_EMAIL }}"
        KANIDM_RAFARIBE_EMAIL2: "{{ .KANIDM_RAFARIBE_EMAIL2 }}"
        KANIDM_RAFARIBE_LEGALNAME: "{{ .KANIDM_RAFARIBE_LEGALNAME }}"
        KANIDM_RAFARIBE_USERNAME: "{{ .KANIDM_RAFARIBE_USERNAME }}"
        KANIDM_WIFE_DISPLAYNAME: "{{ .KANIDM_WIFE_DISPLAYNAME }}"
        KANIDM_WIFE_EMAIL: "{{ .KANIDM_WIFE_EMAIL }}"
        KANIDM_WIFE_EMAIL2: "{{ .KANIDM_WIFE_EMAIL2 }}"
        KANIDM_WIFE_LEGALNAME: "{{ .KANIDM_WIFE_LEGALNAME }}"
        KANIDM_WIFE_USERNAME: "{{ .KANIDM_WIFE_USERNAME }}"
  dataFrom:
    - extract:
        key: /kanidm
