---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret trek
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        ADMIN_EMAIL: "{{ .ADMIN_EMAIL }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: /trek
