---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mealie
  namespace: flux-system
spec:
  targetNamespace: services
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kanidm
      namespace: security
    - name: kopiur
      namespace: kopiur-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 10m
  path: "./kubernetes/apps/services/mealie/app"
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: mealie
      KANIDM_APP_ICON: https://cdn.jsdelivr.net/gh/selfhst/icons/png/mealie.png
      KANIDM_CLIENT_ID_KEY: OIDC_CLIENT_ID
      KANIDM_CLIENT_SECRET_KEY: OIDC_CLIENT_SECRET
      KANIDM_GROUP: household
      KANIDM_ORIGIN_HOST: mealie.rafaribe.com
      KANIDM_REDIRECT_PATH: login
      KOPIUR_CAPACITY: 2Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  components:
    - ../../../../components/kanidm
    - ../../../../components/kopiur/backup-nopvc
