---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app slskd
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        SLSKD_API_KEY: "{{ .SLSKD_API_KEY }}"
        SLSKD_SLSK_PASSWORD: "{{ .SLSKD_SLSK_PASSWORD }}"
        SLSKD_SLSK_USERNAME: "{{ .SLSKD_SLSK_USERNAME }}"
  dataFrom:
    - extract:
        key: /slskd
