---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-mcp-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    creationPolicy: Owner
    name: actual-mcp-secret
  data:
    - remoteRef:
        key: /actual
        property: ACTUAL_PASSWORD
      secretKey: ACTUAL_PASSWORD
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-mcp-secret-sync-id
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    creationPolicy: Owner
    name: actual-mcp-secret-sync-id
  data:
    - remoteRef:
        key: /actual
        property: ACTUAL_SYNC_ID
      secretKey: ACTUAL_SYNC_ID
