---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret portabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        AUTH_DEFAULT_PASSWORD: "{{ .AUTH_DEFAULT_PASSWORD }}"
        AUTH_DEFAULT_USER: "{{ .AUTH_DEFAULT_USER }}"
        AUTH_DEFAULT_USER_NAME: "{{ .AUTH_DEFAULT_USER_NAME }}"
        PROJECT_SECRET: "{{ .PROJECT_SECRET }}"
  dataFrom:
    - extract:
        key: /portabase
