---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-mcp-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    creationPolicy: Owner
    name: grafana-mcp-secret
  data:
    - remoteRef:
        key: /grafana
        property: GRAFANA_MCP_API_KEY
      secretKey: GRAFANA_API_KEY
