---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name linkding
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # Database Configuration
        LD_DB_ENGINE: sqlite
        # General Configuration
        LD_SUPERUSER_NAME: "{{ .LD_SUPERUSER_NAME }}"
        LD_SUPERUSER_PASSWORD: "{{ .LD_SUPERUSER_PASSWORD }}"
        # OIDC Configuration
        LD_ENABLE_OIDC: "True"
        OIDC_OP_AUTHORIZATION_ENDPOINT: "https://idm.rafaribe.com/ui/oauth2"
        OIDC_OP_TOKEN_ENDPOINT: "https://idm.rafaribe.com/oauth2/token"
        OIDC_OP_USER_ENDPOINT: "https://idm.rafaribe.com/oauth2/openid/linkding/userinfo"
        OIDC_OP_JWKS_ENDPOINT: "https://idm.rafaribe.com/oauth2/openid/linkding/public_key.jwk"
        OIDC_RP_SIGN_ALGO: "ES256"
  dataFrom:
    - extract:
        key: /linkding
