---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app musicbrainz-picard
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  interval: 30m
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
    controllers:
      musicbrainz-picard:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/rafaribe/musicbrainz-picard
              tag: 2.13.3
            env:
              DISPLAY_HEIGHT: "1080"
              DISPLAY_WIDTH: "1920"
              TZ: Europe/Lisbon
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 5800
                  initialDelaySeconds: 10
                  periodSeconds: 10
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 5
                  periodSeconds: 5
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 10m
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: false
    persistence:
      config:
        existingClaim: musicbrainz-picard
        globalMounts:
          - path: /config
      storage:
        type: nfs
        server: truenas.rafaribe.com
        path: /mnt/tank/media
        globalMounts:
          - path: /storage
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    route:
      app:
        hostnames: ["picard.rafaribe.com"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
